// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateManySetting implements pgx.CopyFromSource.
type iteratorForCreateManySetting struct {
	rows                 []*CreateManySettingParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManySetting) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManySetting) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].RelationID,
		r.rows[0].NickName,
	}, nil
}

func (r iteratorForCreateManySetting) Err() error {
	return nil
}

func (q *Queries) CreateManySetting(ctx context.Context, arg []*CreateManySettingParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"setting"}, []string{"account_id", "relation_id", "nick_name"}, &iteratorForCreateManySetting{rows: arg})
}
