// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: file.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
insert into file
    (file_name, file_type, file_size, key, url, relation_id, account_id)
values (?, ?, ?, ?, ?, ?, ?)
returning id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
`

type CreateFileParams struct {
	FileName   string `json:"file_name"`
	FileType   string `json:"file_type"`
	FileSize   int64  `json:"file_size"`
	Key        string `json:"key"`
	Url        string `json:"url"`
	RelationID string `json:"relation_id"`
	AccountID  string `json:"account_id"`
}

func (q *Queries) CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Key,
		arg.Url,
		arg.RelationID,
		arg.AccountID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
delete
from file
where id=?
`

func (q *Queries) DeleteFileByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFileByID, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
select id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
from file
where id=?
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (*File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const getFileByRelationID = `-- name: GetFileByRelationID :many
select id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
from file
where relation_id=?
`

func (q *Queries) GetFileByRelationID(ctx context.Context, relationID sql.NullInt64) ([]*File, error) {
	rows, err := q.db.Query(ctx, getFileByRelationID, relationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Key,
			&i.Url,
			&i.RelationID,
			&i.AccountID,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
