// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: group_notify.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const createGroupNotify = `-- name: CreateGroupNotify :one
insert into group_notify
(id, relation_id, msg_content, msg_expand, account_id, create_at, read_ids)
values (?, ?, ?, ?, ?, ?, ?)
returning id, relation_id, msg_content, msg_expand, account_id, create_at, read_ids, msg_content_tsv
`

type CreateGroupNotifyParams struct {
	ID         int64         `json:"id"`
	RelationID sql.NullInt64 `json:"relation_id"`
	MsgContent string        `json:"msg_content"`
	MsgExpand  pgtype.JSON   `json:"msg_expand"`
	AccountID  sql.NullInt64 `json:"account_id"`
	CreateAt   time.Time     `json:"create_at"`
	ReadIds    []int64       `json:"read_ids"`
}

func (q *Queries) CreateGroupNotify(ctx context.Context, arg *CreateGroupNotifyParams) (*GroupNotify, error) {
	row := q.db.QueryRow(ctx, createGroupNotify,
		arg.ID,
		arg.RelationID,
		arg.MsgContent,
		arg.MsgExpand,
		arg.AccountID,
		arg.CreateAt,
		arg.ReadIds,
	)
	var i GroupNotify
	err := row.Scan(
		&i.ID,
		&i.RelationID,
		&i.MsgContent,
		&i.MsgExpand,
		&i.AccountID,
		&i.CreateAt,
		&i.ReadIds,
		&i.MsgContentTsv,
	)
	return &i, err
}

const deleteGroupNotify = `-- name: DeleteGroupNotify :exec
delete
from group_notify
where id = ?
`

func (q *Queries) DeleteGroupNotify(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGroupNotify, id)
	return err
}

const getGroupNotifyByID = `-- name: GetGroupNotifyByID :one
select id, relation_id, msg_content, msg_expand, account_id, create_at, read_ids, msg_content_tsv
from group_notify
where id = ?
limit 1
`

func (q *Queries) GetGroupNotifyByID(ctx context.Context, id int64) (*GroupNotify, error) {
	row := q.db.QueryRow(ctx, getGroupNotifyByID, id)
	var i GroupNotify
	err := row.Scan(
		&i.ID,
		&i.RelationID,
		&i.MsgContent,
		&i.MsgExpand,
		&i.AccountID,
		&i.CreateAt,
		&i.ReadIds,
		&i.MsgContentTsv,
	)
	return &i, err
}

const updateGroupNotify = `-- name: UpdateGroupNotify :one
update group_notify
set id         = ?,
    relation_id= ?,
    msg_content= ?,
    msg_expand = ?,
    account_id = ?,
    create_at  = ?,
    read_ids   = ?
where id=?
returning id, relation_id, msg_content, msg_expand, account_id, create_at, read_ids, msg_content_tsv
`

type UpdateGroupNotifyParams struct {
	ID         int64         `json:"id"`
	RelationID sql.NullInt64 `json:"relation_id"`
	MsgContent string        `json:"msg_content"`
	MsgExpand  pgtype.JSON   `json:"msg_expand"`
	AccountID  sql.NullInt64 `json:"account_id"`
	CreateAt   time.Time     `json:"create_at"`
	ReadIds    []int64       `json:"read_ids"`
	ID_2       int64         `json:"id_2"`
}

func (q *Queries) UpdateGroupNotify(ctx context.Context, arg *UpdateGroupNotifyParams) (*GroupNotify, error) {
	row := q.db.QueryRow(ctx, updateGroupNotify,
		arg.ID,
		arg.RelationID,
		arg.MsgContent,
		arg.MsgExpand,
		arg.AccountID,
		arg.CreateAt,
		arg.ReadIds,
		arg.ID_2,
	)
	var i GroupNotify
	err := row.Scan(
		&i.ID,
		&i.RelationID,
		&i.MsgContent,
		&i.MsgExpand,
		&i.AccountID,
		&i.CreateAt,
		&i.ReadIds,
		&i.MsgContentTsv,
	)
	return &i, err
}
