basePath: /api
definitions:
  common.State:
    properties:
      data:
        description: 失败时返回空
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  common.Token:
    properties:
      expired_at:
        description: token过期时间
        type: string
      token:
        description: token
        type: string
    type: object
  reply.AccountInfo:
    properties:
      account_id:
        description: 账号ID
        type: integer
      avatar:
        description: 头像
        type: string
      name:
        description: 名称
        type: string
    type: object
  reply.CreateAccount:
    properties:
      account_Token:
        $ref: '#/definitions/common.Token'
        description: 账号Token
      avatar:
        description: 头像
        type: string
      id:
        description: 账号ID
        type: integer
      name:
        description: 名称
        type: string
    type: object
  reply.ExistEmail:
    properties:
      exist:
        type: boolean
    type: object
  reply.GetAccountByID:
    properties:
      avatar:
        description: 头像
        type: string
      create_at:
        description: 创建时间
        type: string
      gender:
        description: 性别
        type: string
      id:
        description: 账号ID
        type: integer
      name:
        description: 名称
        type: string
      signature:
        description: 个性签名
        type: string
    type: object
  reply.GetAccountToken:
    properties:
      account_token:
        $ref: '#/definitions/common.Token'
        description: 账号Token
    type: object
  reply.GetAccountsByName:
    properties:
      list:
        description: 账号列表
        items:
          $ref: '#/definitions/reply.AccountInfo'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  reply.GetAccountsByUserID:
    properties:
      list:
        description: 账号列表
        items:
          $ref: '#/definitions/reply.AccountInfo'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  reply.Login:
    properties:
      user_info:
        $ref: '#/definitions/reply.UserInfo'
        description: 用户信息
      user_token:
        $ref: '#/definitions/common.Token'
        description: 用户令牌
    type: object
  reply.Register:
    properties:
      user_info:
        $ref: '#/definitions/reply.UserInfo'
        description: 用户信息
      user_token:
        $ref: '#/definitions/common.Token'
        description: 用户令牌
    type: object
  reply.UserInfo:
    properties:
      create_at:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: user id
        type: integer
    type: object
  request.CreateAccount:
    properties:
      avatar:
        description: 头像
        maxLength: 100
        minLength: 1
        type: string
      name:
        description: 名称
        maxLength: 20
        minLength: 1
        type: string
    required:
    - avatar
    - name
    type: object
  request.DeleteAccount:
    properties:
      account_id:
        description: 账号ID
        minimum: 1
        type: integer
    required:
    - account_id
    type: object
  request.Login:
    properties:
      email:
        description: 邮箱
        maxLength: 50
        type: string
      password:
        description: 密码
        maxLength: 50
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.Register:
    properties:
      code:
        description: 验证码
        maxLength: 6
        minLength: 6
        type: string
      email:
        description: 邮箱
        maxLength: 50
        type: string
      password:
        description: 密码
        maxLength: 50
        minLength: 6
        type: string
    required:
    - code
    - email
    - password
    type: object
  request.SendEmail:
    properties:
      email:
        description: 邮箱
        maxLength: 50
        type: string
    required:
    - email
    type: object
  request.UpdateAccount:
    properties:
      avatar:
        description: 头像
        maxLength: 100
        minLength: 1
        type: string
      gender:
        description: 性别
        enum:
        - 男
        - 女
        - 未知
        type: string
      name:
        description: 名称
        maxLength: 20
        minLength: 1
        type: string
      signature:
        description: 个性签名
        maxLength: 200
        minLength: 1
        type: string
    required:
    - avatar
    - gender
    - name
    - signature
    type: object
  request.UpdateUserEmail:
    properties:
      code:
        description: 验证码
        maxLength: 6
        minLength: 6
        type: string
      email:
        description: 邮箱
        maxLength: 50
        type: string
    required:
    - code
    - email
    type: object
  request.UpdateUserPassword:
    properties:
      code:
        description: 验证码
        maxLength: 6
        minLength: 6
        type: string
      new_password:
        description: 新密码
        maxLength: 50
        minLength: 6
        type: string
    required:
    - code
    - new_password
    type: object
host: chat.humraja.xyz
info:
  contact: {}
  description: 在线聊天系统
  license:
    name: raja,chong
  title: chat
  version: "1.0"
paths:
  /api/account/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 创建账号信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2008:身份验证失败 2012:账号数量超过限制 2011:账号名已经存在
            2007:身份不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.CreateAccount'
              type: object
      summary: 创建账号
      tags:
      - account
  /api/account/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 账号ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeleteAccount'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败 2009:权限不足 2010:账号不存在
          schema:
            $ref: '#/definitions/common.State'
      summary: 删除账户
      tags:
      - account
  /api/account/info:
    get:
      consumes:
      - application/json
      parameters:
      - description: 账号ID
        in: query
        minimum: 1
        name: accountID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2009:权限不足 2010:账号不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountByID'
              type: object
      summary: 获取账户信息
      tags:
      - account
  /api/account/infos/name:
    get:
      consumes:
      - application/json
      parameters:
      - description: 搜索名称
        in: query
        maxLength: 20
        minLength: 1
        name: name
        required: true
        type: string
      - description: 第几页
        in: query
        name: page
        type: integer
      - description: 每页大小
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountsByName'
              type: object
      summary: 通过昵称查找账户
      tags:
      - account
  /api/account/infos/user:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 1003:系统错误 2008:身份验证失败 2010:账号不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountsByUserID'
              type: object
      summary: 获取用户的所有账户
      tags:
      - account
  /api/account/token:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 账号ID
        in: query
        minimum: 1
        name: accountID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误  1003:系统错误 2007:身份不存在 2008:身份验证失败 2009:权限不足 2010:账号不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountToken'
              type: object
      summary: 获取账号令牌
      tags:
      - account
  /api/account/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 账户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 账号信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败
          schema:
            $ref: '#/definitions/common.State'
      summary: 更新账户信息
      tags:
      - account
  /api/email/exist:
    get:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: query
        maxLength: 50
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.ExistEmail'
              type: object
      summary: 是否已经存在该email
      tags:
      - email
  /api/email/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2006:邮箱已经注册 2003:邮件发送频繁，请稍后再试
          schema:
            $ref: '#/definitions/common.State'
      summary: 发送邮件
      tags:
      - email
  /api/user/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2001:用户不存在 2007:身份不存在 2008:身份验证失败
          schema:
            $ref: '#/definitions/common.State'
      security:
      - BasicAuth: []
      summary: 删除当前用户
      tags:
      - user
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登陆信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2001:用户不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.Login'
              type: object
      summary: 用户登陆
      tags:
      - user
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 2004:邮箱验证码校验失败 2006:邮箱已经注册 '
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.Register'
              type: object
      summary: 用户注册
      tags:
      - user
  /api/user/update/email:
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 新邮箱和验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2001:用户不存在 2004:邮箱验证码校验失败 2005:邮箱相同 2006:邮箱已经注册
            2007:身份不存在 2008:身份验证失败
          schema:
            $ref: '#/definitions/common.State'
      security:
      - BasicAuth: []
      summary: 更新用户邮箱
      tags:
      - user
  /api/user/update/pwd:
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 旧密码和新密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2001:用户不存在 2004:邮箱验证码校验失败 2007:身份不存在 2008:身份验证失败
          schema:
            $ref: '#/definitions/common.State'
      security:
      - BasicAuth: []
      summary: 更新用户密码
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
